### ISSUE TITLE
Render lags and issues with LoliASM 5.12

### ISSUE THREAD

**Issue by HaHaWTH** [LoliKingdom/LoliASM#176]
Environment: Forge 14.23.5.2860, Windows 7
I updated LoliASM to 5.12 on my client, when entering the world, it causes serious render lag, after downgrading to v5.6 of LoliASM, the issue won't appear anymore.
[config.txt](https://github.com/LoliKingdom/LoliASM/files/11664092/config.txt)
[latest.log](https://github.com/LoliKingdom/LoliASM/files/11664059/latest.log)
[debug.log](https://github.com/LoliKingdom/LoliASM/files/11664062/debug.log)

With LoliASM 5.12 installed: 

![2023-06-06_19 33 01](https://github.com/LoliKingdom/LoliASM/assets/102713261/8fdd898b-5b41-4c6c-8b32-1b3f1d8b5461)
![2023-06-06_19 33 14](https://github.com/LoliKingdom/LoliASM/assets/102713261/57a93f05-a3a7-4925-a145-a09ebded98af)
maybe I could only use LoliASM 5.6 ;-(
I can send the client files if needed :)
GPU: ATI(AMD) Radeon HD 4250(Integrated Graphics)

**Comment by embeddedt** [comment]
Probably the issue I fixed here: https://github.com/LoliKingdom/LoliASM/pull/175

**Comment by HaHaWTH** [comment]
> Probably the issue I fixed here: #175

I've tested it just now, rendering is better than before, but it still happens, also caused serious integrated server lag:(
![2023-06-08_17 01 15](https://github.com/LoliKingdom/LoliASM/assets/102713261/b68652d6-e22e-4be8-bc55-9749ae226cd4)
![2023-06-08_17 01 29](https://github.com/LoliKingdom/LoliASM/assets/102713261/7907e8c9-4a11-4bd3-83fd-176f786e5cce)
d70-4e26-8376-147026e56545)
![2023-06-08_17 01 44](https://github.com/LoliKingdom/LoliASM/assets/102713261/0b676ab2-7795-439a-8510-d474be45c914)
I tried to run client without VintageFix, and the situation is getting worse

**Comment by HaHaWTH** [comment]
and after install LoliASM5.12, when playing noteblocks, it may cause music records duplication, when broke the noteblock, the music will be still on playing

**Comment by Rongmario** [comment]
Can you use [spark](https://www.curseforge.com/minecraft/mc-mods/spark/files/3245793) to profile your game?

**Comment by embeddedt** [comment]
You should also test performance of LoliASM without VintageFix installed, as otherwise it's hard to know where the problem is.

**Comment by HaHaWTH** [comment]
OK, I am profiling and the result will be uploaded later

**Comment by embeddedt** [comment]
Can you use `/sparkc`? This is a server profile.

**Comment by HaHaWTH** [comment]
Here it is: https://spark.lucko.me/qh7q4T6lv6

**Comment by HaHaWTH** [comment]
> It seems to once again be a server profile. (Note the `Server thread` on the page.)

I didn't copy the right link:(

**Comment by Rongmario** [comment]
@HaHaWTH can you turn on VBO?

**Comment by HaHaWTH** [comment]
> @HaHaWTH can you turn on VBO?

Unfortunately, I can't turn it on because of the old Graphic card:(

**Comment by HaHaWTH** [comment]
I will try with only LoliASM and MixinBooter installed later

**Comment by HaHaWTH** [comment]
@Rongmario Sorry to bother you, but when I tested with only MixinBooter, LoliASM5.12 installed, the problem didn't be solved and it is getting worse. Links: https://spark.lucko.me/24RyO5B4jO

**Comment by Rongmario** [comment]
From the report it seems like you'll still run badly without LoliASM...

**Comment by HaHaWTH** [comment]
But.....when I disabled the mod, it won't be laggy....

**Comment by KorewaLidesu** [comment]
> But.....when I disabled the mod, it won't be laggy....

Try each version between 5.6 and 5.12, check which mod version period cause the issue to happen.

**Comment by HaHaWTH** [comment]
After all the tests, the issue occurs since v5.7 update

**Comment by HaHaWTH** [comment]
Sorry for not responsing

**Comment by HaHaWTH** [comment]
Will the issue be solved in the future? I could only use v5.6 now:(

**Comment by embeddedt** [comment]
Does 5.14 resolve this?

**Comment by HaHaWTH** [comment]
> Does 5.14 resolve this?

Sorry for the late response, but this issue still happens :(

**Comment by HaHaWTH** [comment]
Solved, I am using an extremely old GPU and Minecraft takes up of 100% GPU usage and causes the render lag.

**Comment by HaHaWTH** [comment]
Solved, I am using an extremely old GPU and Minecraft takes up of 100% GPU usage and causes the render lag.
